--
-- PostgreSQL database dump
--

\restrict mE1ibhHNwwgxE2hSGmXcCjcSF9pwYa65KWaQzOVUz6QjKOcsgYUaRcajJjXDFLF

-- Dumped from database version 16.10
-- Dumped by pg_dump version 16.10

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: inventory_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.inventory_items VALUES ('item-007', 'kitchen', '생크림', 'food', 'refrigerated', '유제품&치즈', '개', 29, 3, 1, 10, '[{"season": "winter", "requiredStock": 13}, {"season": "spring", "requiredStock": 13}, {"season": "summer", "requiredStock": 13}, {"season": "fall", "requiredStock": 13}]', '["tag-k4", "tag-k5", "tag-k10"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-008', 'kitchen', '비건생크림', 'food', 'refrigerated', '유제품&치즈', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k6"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k2');
INSERT INTO public.inventory_items VALUES ('item-009', 'kitchen', '마가린', 'food', 'refrigerated', '유제품&치즈', '개', 2, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k6"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-010', 'kitchen', '마스카포네치즈', 'food', 'refrigerated', '유제품&치즈', '개', 21, 2, 1, 6, '[{"season": "winter", "requiredStock": 8}, {"season": "spring", "requiredStock": 8}, {"season": "summer", "requiredStock": 8}, {"season": "fall", "requiredStock": 8}]', '["tag-k10"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-011', 'kitchen', '과일치즈', 'food', 'refrigerated', '유제품&치즈', '개', 3, 0, 1, 2, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '["tag-k9"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-012', 'kitchen', '스모크치즈', 'food', 'refrigerated', '유제품&치즈', '개', 1, 0, 2, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k9"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-013', 'kitchen', '크림치즈', 'food', 'refrigerated', '유제품&치즈', '개', 5, 0, 1, 3, '[{"season": "winter", "requiredStock": 3}, {"season": "spring", "requiredStock": 3}, {"season": "summer", "requiredStock": 3}, {"season": "fall", "requiredStock": 3}]', '["tag-k9"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-014', 'kitchen', '살라미', 'food', 'refrigerated', '유제품&치즈', '개', 2, 0, 1, 2, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '["tag-k9"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-015', 'kitchen', '하몽', 'food', 'refrigerated', '가공육류&알', '개', 2, 0, 1, 2, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '["tag-k9"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-001', 'kitchen', '슬라이스 치즈', 'food', 'refrigerated', '유제품&치즈', '개', 0, 0.1, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k1"]', '2026-01-12', 'ordered', 1, '2026-01-11T14:53:34.600Z', 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-002', 'kitchen', '까망베르 치즈', 'food', 'refrigerated', '유제품&치즈', '개', 8, 2, 1, 10, '[{"season": "winter", "requiredStock": 12}, {"season": "spring", "requiredStock": 12}, {"season": "summer", "requiredStock": 12}, {"season": "fall", "requiredStock": 12}]', '["tag-k2"]', '2026-01-12', 'ordered', 4, '2026-01-11T14:53:36.632Z', 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-003', 'kitchen', '그라나파다노', 'food', 'refrigerated', '유제품&치즈', '개', 2, 0, 1, 3, '[{"season": "winter", "requiredStock": 3}, {"season": "spring", "requiredStock": 3}, {"season": "summer", "requiredStock": 3}, {"season": "fall", "requiredStock": 3}]', '["tag-k3", "tag-k4", "tag-k8"]', '2026-01-12', 'ordered', 1, '2026-01-11T14:53:37.823Z', 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-005', 'kitchen', '난황', 'food', 'refrigerated', '유제품&치즈', '개', 0, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k10", "tag-k5"]', '2026-01-12', 'ordered', 1, '2026-01-11T14:53:39.923Z', NULL);
INSERT INTO public.inventory_items VALUES ('item-006', 'kitchen', '우유', 'food', 'refrigerated', '유제품&치즈', '개', 2, 1, 1, 2, '[{"season": "winter", "requiredStock": 3}, {"season": "spring", "requiredStock": 3}, {"season": "summer", "requiredStock": 3}, {"season": "fall", "requiredStock": 3}]', '["tag-k1", "tag-k8"]', '2026-01-12', 'ordered', 1, '2026-01-11T14:53:41.176Z', 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-016', 'kitchen', '달걀', 'food', 'refrigerated', '가공육류&알', '개', 2, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k5", "tag-k8"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-017', 'kitchen', '딜', 'food', 'refrigerated', '잎채소&허브류', 'g', 100, 20, 50, 90, '[{"season": "winter", "requiredStock": 100}, {"season": "spring", "requiredStock": 100}, {"season": "summer", "requiredStock": 100}, {"season": "fall", "requiredStock": 100}]', '["tag-k3", "tag-k2", "tag-k11"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k3');
INSERT INTO public.inventory_items VALUES ('item-018', 'kitchen', '처빌', 'food', 'refrigerated', '잎채소&허브류', '개', 2, 0, 2, 0, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '["tag-k6", "tag-k11", "tag-k16"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-019', 'kitchen', '어린잎250g', 'food', 'refrigerated', '잎채소&허브류', '개', 2, 0.3, 2, 1, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '["tag-k11"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-022', 'kitchen', '타임', 'food', 'refrigerated', '잎채소&허브류', '개', 3, 0.5, 2, 2, '[{"season": "winter", "requiredStock": 3}, {"season": "spring", "requiredStock": 3}, {"season": "summer", "requiredStock": 3}, {"season": "fall", "requiredStock": 3}]', '["tag-k15"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k3');
INSERT INTO public.inventory_items VALUES ('item-024', 'kitchen', '전처리양파_초밥', 'food', 'refrigerated', '잎채소&허브류', '개', 10, 0, 2, 10, '[{"season": "winter", "requiredStock": 10}, {"season": "spring", "requiredStock": 10}, {"season": "summer", "requiredStock": 10}, {"season": "fall", "requiredStock": 10}]', '["tag-k1"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-025', 'kitchen', '깐양파', 'food', 'refrigerated', '잎채소&허브류', '개', 2, 0, 2, 2, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '["tag-k15"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-026', 'kitchen', '파프리카', 'food', 'refrigerated', '잎채소&허브류', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k7"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-027', 'kitchen', '토마토', 'food', 'refrigerated', '잎채소&허브류', '개', 4, 1, 1, 3, '[{"season": "winter", "requiredStock": 4}, {"season": "spring", "requiredStock": 4}, {"season": "summer", "requiredStock": 4}, {"season": "fall", "requiredStock": 4}]', '["tag-k6", "tag-k7"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-028', 'kitchen', '방울토마토', 'food', 'refrigerated', '잎채소&허브류', '개', 3, 1, 1, 2, '[{"season": "winter", "requiredStock": 3}, {"season": "spring", "requiredStock": 3}, {"season": "summer", "requiredStock": 3}, {"season": "fall", "requiredStock": 3}]', '["tag-k8", "tag-k11", "tag-k13"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-029', 'kitchen', '깐마늘', 'food', 'refrigerated', '잎채소&허브류', '개', 1, 0.1, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k7"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-031', 'kitchen', '꽈리고추', 'food', 'refrigerated', '채소&버섯&과일', '개', 0.2, 0, 1, 0, '[{"season": "winter", "requiredStock": 0.1}, {"season": "spring", "requiredStock": 0.1}, {"season": "summer", "requiredStock": 0.1}, {"season": "fall", "requiredStock": 0.1}]', '["tag-k13"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-032', 'kitchen', '양송이', 'food', 'refrigerated', '채소&버섯&과일', '개', 3, 1, 1, 2, '[{"season": "winter", "requiredStock": 3}, {"season": "spring", "requiredStock": 3}, {"season": "summer", "requiredStock": 3}, {"season": "fall", "requiredStock": 3}]', '["tag-k4", "tag-k3", "tag-k13"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-033', 'kitchen', '당근', 'food', 'refrigerated', '채소&버섯&과일', '개', 2, 0.5, 1, 1, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '["tag-k15"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-034', 'kitchen', '샐러리', 'food', 'refrigerated', '채소&버섯&과일', '개', 2, 0.5, 1, 1, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '["tag-k15"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-035', 'kitchen', '레몬', 'food', 'refrigerated', '채소&버섯&과일', '개', 30, 5, 2, 10, '[{"season": "winter", "requiredStock": 20}, {"season": "spring", "requiredStock": 20}, {"season": "summer", "requiredStock": 20}, {"season": "fall", "requiredStock": 20}]', '["tag-k3", "tag-k2"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k3');
INSERT INTO public.inventory_items VALUES ('item-030', 'kitchen', '편마늘', 'food', 'refrigerated', '채소&버섯&과일', '개', 2, 1, 2, 2, '[{"season": "winter", "requiredStock": 4}, {"season": "spring", "requiredStock": 4}, {"season": "summer", "requiredStock": 4}, {"season": "fall", "requiredStock": 4}]', '["tag-k13"]', '2026-01-12', 'ordered', 2, '2026-01-11T14:53:43.415Z', 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-036', 'kitchen', '청포도or샤인머스캣', 'food', 'refrigerated', '채소&버섯&과일', '개', 3, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k5", "tag-k9"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k2');
INSERT INTO public.inventory_items VALUES ('item-038', 'kitchen', '마요네즈', 'food', 'refrigerated', '소스&절임류', '개', 1, 0, 2, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k7"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-039', 'kitchen', '라임주스', 'food', 'refrigerated', '소스&절임류', '개', 1, 0, 2, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k8"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-040', 'kitchen', '카스텔베트라노', 'food', 'refrigerated', '소스&절임류', '개', 7, 1, 2, 4, '[{"season": "winter", "requiredStock": 6}, {"season": "spring", "requiredStock": 6}, {"season": "summer", "requiredStock": 6}, {"season": "fall", "requiredStock": 6}]', '["tag-k9", "tag-k15"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k4');
INSERT INTO public.inventory_items VALUES ('item-041', 'kitchen', '아르티지아나트러플소스', 'food', 'refrigerated', '소스&절임류', '개', 7, 1, 2, 4, '[{"season": "winter", "requiredStock": 6}, {"season": "spring", "requiredStock": 6}, {"season": "summer", "requiredStock": 6}, {"season": "fall", "requiredStock": 6}]', '["tag-k15"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k4');
INSERT INTO public.inventory_items VALUES ('item-042', 'kitchen', '굴소스', 'food', 'refrigerated', '소스&절임류', '개', 2, 0, 1, 2, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '["tag-k1"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-043', 'kitchen', '케이퍼', 'food', 'refrigerated', '소스&절임류', '개', 2, 0.1, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k11"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-044', 'kitchen', '앤초비', 'food', 'refrigerated', '소스&절임류', '개', 1, 0.1, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k13"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-047', 'kitchen', '모짜렐라', 'food', 'frozen', '냉동유제품', '개', 4, 0.5, 3, 4, '[{"season": "winter", "requiredStock": 4}, {"season": "spring", "requiredStock": 4}, {"season": "summer", "requiredStock": 4}, {"season": "fall", "requiredStock": 4}]', '["tag-k1"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-048', 'kitchen', '버터', 'food', 'frozen', '냉동유제품', '개', 19, 4, 1, 15, '[{"season": "winter", "requiredStock": 19}, {"season": "spring", "requiredStock": 19}, {"season": "summer", "requiredStock": 19}, {"season": "fall", "requiredStock": 19}]', '["tag-k1", "tag-k3", "tag-k5", "tag-k8"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-049', 'kitchen', '베이컨', 'food', 'frozen', '냉동육류', '개', 11, 1, 2, 6, '[{"season": "winter", "requiredStock": 8}, {"season": "spring", "requiredStock": 8}, {"season": "summer", "requiredStock": 8}, {"season": "fall", "requiredStock": 8}]', '["tag-k3", "tag-k5"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-050', 'kitchen', '잠봉', 'food', 'frozen', '냉동육류', '개', 7, 1, 2, 5, '[{"season": "winter", "requiredStock": 6}, {"season": "spring", "requiredStock": 6}, {"season": "summer", "requiredStock": 6}, {"season": "fall", "requiredStock": 6}]', '["tag-k4", "tag-k9"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-051', 'kitchen', '우민찌', 'food', 'frozen', '냉동육류', '개', 16, 2, 2, 6, '[{"season": "winter", "requiredStock": 10}, {"season": "spring", "requiredStock": 10}, {"season": "summer", "requiredStock": 10}, {"season": "fall", "requiredStock": 10}]', '["tag-k1"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-052', 'kitchen', '돈민찌', 'food', 'frozen', '냉동육류', '개', 2, 0, 2, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k1"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-053', 'kitchen', '새우', 'food', 'frozen', '냉동해산물', '개', 3, 0.5, 1, 3, '[{"season": "winter", "requiredStock": 3}, {"season": "spring", "requiredStock": 3}, {"season": "summer", "requiredStock": 3}, {"season": "fall", "requiredStock": 3}]', '["tag-k13", "tag-k3"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-054', 'kitchen', '연어', 'food', 'frozen', '냉동해산물', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k11"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-046', 'kitchen', '생트러플', 'food', 'refrigerated', '특수발주', '개', 0, 0, 2, 1, '[{"season": "winter", "requiredStock": 50}, {"season": "spring", "requiredStock": 50}, {"season": "summer", "requiredStock": 50}, {"season": "fall", "requiredStock": 50}]', '["tag-k15"]', '2026-01-12', 'ordered', 50, '2026-01-11T14:53:55.607Z', NULL);
INSERT INTO public.inventory_items VALUES ('item-056', 'kitchen', '브리오슈', 'food', 'frozen', '냉동빵류', '개', 2, 1, 1, 1, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '["tag-k5"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k2');
INSERT INTO public.inventory_items VALUES ('item-057', 'kitchen', '냉동브로콜리', 'food', 'frozen', '냉동기타', '개', 7, 1, 1, 3, '[{"season": "winter", "requiredStock": 4}, {"season": "spring", "requiredStock": 4}, {"season": "summer", "requiredStock": 4}, {"season": "fall", "requiredStock": 4}]', '["tag-k15", "tag-k13"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-058', 'kitchen', '메쉬드', 'food', 'frozen', '냉동기타', '개', 4, 1, 1, 3, '[{"season": "winter", "requiredStock": 4}, {"season": "spring", "requiredStock": 4}, {"season": "summer", "requiredStock": 4}, {"season": "fall", "requiredStock": 4}]', '[]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-059', 'kitchen', '라즈베리', 'food', 'frozen', '냉동기타', '개', 2, 0, 1, 2, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '["tag-k5", "tag-k9"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-060', 'kitchen', '샬롯', 'food', 'room-temp', '상온채소', '개', 3000, 50, 2, 500, '[{"season": "winter", "requiredStock": 600}, {"season": "spring", "requiredStock": 600}, {"season": "summer", "requiredStock": 600}, {"season": "fall", "requiredStock": 600}]', '["tag-k8", "tag-k16"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k3');
INSERT INTO public.inventory_items VALUES ('item-061', 'kitchen', '크래커', 'food', 'room-temp', '가공식품', '개', 4, 0.1, 1, 3, '[{"season": "winter", "requiredStock": 3}, {"season": "spring", "requiredStock": 3}, {"season": "summer", "requiredStock": 3}, {"season": "fall", "requiredStock": 3}]', '["tag-k2", "tag-k9"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-063', 'kitchen', '리가토니', 'food', 'room-temp', '가공식품', '개', 10, 2, 1, 8, '[{"season": "winter", "requiredStock": 10}, {"season": "spring", "requiredStock": 10}, {"season": "summer", "requiredStock": 10}, {"season": "fall", "requiredStock": 10}]', '["tag-k4"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-064', 'kitchen', '사보이아르디', 'food', 'room-temp', '가공식품', '개', 8, 0.5, 1, 2, '[{"season": "winter", "requiredStock": 3}, {"season": "spring", "requiredStock": 3}, {"season": "summer", "requiredStock": 3}, {"season": "fall", "requiredStock": 3}]', '["tag-k10"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-065', 'kitchen', '포마스', 'food', 'room-temp', '오일', '개', 2, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k5", "tag-k8", "tag-k15", "tag-k13"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-066', 'kitchen', '엑스트라버진', 'food', 'room-temp', '오일', '개', 2, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k6", "tag-k7", "tag-k9", "tag-k11"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-067', 'kitchen', '블랙올리브', 'food', 'room-temp', '오일', '개', 4, 1, 1, 1, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '["tag-k3", "tag-k6", "tag-k11"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-068', 'kitchen', '할라피뇨', 'food', 'room-temp', '캔', '개', 3, 0, 1, 0, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '["tag-k1", "tag-k4"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-069', 'kitchen', '롱고바디', 'food', 'room-temp', '캔', '개', 4, 0.5, 1, 1, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '["tag-k7"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-070', 'kitchen', '토마토페이스트', 'food', 'room-temp', '캔', '개', 2, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k6", "tag-k15"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-071', 'kitchen', '팩와인_레드', 'food', 'room-temp', '상온소스', '개', 1, 0, 2, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k15", "tag-k14"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-072', 'kitchen', '팩와인_화이트', 'food', 'room-temp', '상온소스', '개', 1, 0, 2, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '[]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-074', 'kitchen', '화이트와인비네거', 'food', 'room-temp', '상온소스', '개', 2, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k8"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-075', 'kitchen', '샴페인비네거', 'food', 'room-temp', '상온소스', '개', 3, 0, 2, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k16"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-076', 'kitchen', '타바스코150ml', 'food', 'room-temp', '상온소스', '개', 5, 0, 1, 3, '[{"season": "winter", "requiredStock": 3}, {"season": "spring", "requiredStock": 3}, {"season": "summer", "requiredStock": 3}, {"season": "fall", "requiredStock": 3}]', '["tag-k1"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-077', 'kitchen', '메이플시럽', 'food', 'room-temp', '상온소스', '개', 3, 0, 3, 3, '[{"season": "winter", "requiredStock": 3}, {"season": "spring", "requiredStock": 3}, {"season": "summer", "requiredStock": 3}, {"season": "fall", "requiredStock": 3}]', '["tag-k5"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k2');
INSERT INTO public.inventory_items VALUES ('item-079', 'kitchen', '이금기치킨스톡농축액', 'food', 'room-temp', '상온소스', '개', 2, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k12", "tag-k4", "tag-k8", "tag-k15"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-081', 'kitchen', '이탈리안허브시즈닝', 'food', 'room-temp', '상온소스', '개', 3, 0, 1, 1, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '["tag-k1", "tag-k13", "tag-k14"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-082', 'kitchen', '파프리카시즈닝', 'food', 'room-temp', '상온소스', '개', 2, 0, 1, 2, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '["tag-k1", "tag-k7"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-083', 'kitchen', '오레가노', 'food', 'room-temp', '건허브&향신료', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k1"]', '2026-01-11', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-099', 'kitchen', '천일염', 'food', 'room-temp', '가루류', '개', 1, 20.7, 2, 1, '[{"season": "winter", "requiredStock": 0}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k16"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-086', 'kitchen', '백후추', 'food', 'room-temp', '건허브&향신료', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k4"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-087', 'kitchen', '핑크페퍼', 'food', 'room-temp', '건허브&향신료', '개', 1, 0, 2, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '[]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-088', 'kitchen', '베트남고추', 'food', 'room-temp', '건허브&향신료', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k13"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-089', 'kitchen', '시나몬파우더', 'food', 'room-temp', '건허브&향신료', '개', 3, 0, 1, 1, '[{"season": "winter", "requiredStock": 3}, {"season": "spring", "requiredStock": 3}, {"season": "summer", "requiredStock": 3}, {"season": "fall", "requiredStock": 3}]', '["tag-k5"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k2');
INSERT INTO public.inventory_items VALUES ('item-090', 'kitchen', '피칸', 'food', 'room-temp', '건허브&향신료', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k2", "tag-k9"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-091', 'kitchen', '아몬드', 'food', 'room-temp', '견과류&곡물류', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k2", "tag-k7", "tag-k9"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-092', 'kitchen', '캐슈넛', 'food', 'room-temp', '견과류&곡물류', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k2", "tag-k9"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-093', 'kitchen', '오트밀', 'food', 'room-temp', '견과류&곡물류', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k5"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-094', 'kitchen', '해바라기씨', 'food', 'room-temp', '견과류&곡물류', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k5"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-095', 'kitchen', '호박씨', 'food', 'room-temp', '견과류&곡물류', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k5"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-096', 'kitchen', '헤이즐넛', 'food', 'room-temp', '견과류&곡물류', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k5"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-097', 'kitchen', '코코넛롱(코코넛슬라이스)', 'food', 'room-temp', '견과류&곡물류', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k5"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-100', 'kitchen', '백설탕', 'food', 'room-temp', '가루류', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k5", "tag-k6", "tag-k10"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-101', 'kitchen', '황설탕', 'food', 'room-temp', '가루류', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k9", "tag-k5"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-102', 'kitchen', '흑설탕', 'food', 'room-temp', '가루류', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k9"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-103', 'kitchen', '박력분', 'food', 'room-temp', '가루류', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k14", "tag-k4"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-085', 'kitchen', '통흑후추', 'food', 'room-temp', '건허브&향신료', '개', 2, 0, 1, 1, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '["tag-k6", "tag-k8", "tag-k9", "tag-k11"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-107', 'kitchen', '니트릴장갑S', 'non-food', 'room-temp', '소모품', '개', 2, 0, 1, 2, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '[]', NULL, 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-108', 'kitchen', '니트릴장갑L', 'non-food', 'room-temp', '소모품', '개', 2, 0, 1, 2, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '[]', NULL, 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-109', 'kitchen', '비닐(소)', 'non-food', 'room-temp', '소모품', '개', 8, 0, 1, 8, '[{"season": "winter", "requiredStock": 8}, {"season": "spring", "requiredStock": 8}, {"season": "summer", "requiredStock": 8}, {"season": "fall", "requiredStock": 8}]', '[]', NULL, 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-110', 'kitchen', '비닐(대)', 'non-food', 'room-temp', '소모품', '개', 3, 0, 1, 3, '[{"season": "winter", "requiredStock": 3}, {"season": "spring", "requiredStock": 3}, {"season": "summer", "requiredStock": 3}, {"season": "fall", "requiredStock": 3}]', '[]', NULL, 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-111', 'kitchen', '위생장갑', 'non-food', 'room-temp', '소모품', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '[]', NULL, 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-112', 'kitchen', '종이호일', 'non-food', 'room-temp', '소모품', '개', 3, 0, 1, 3, '[{"season": "winter", "requiredStock": 3}, {"season": "spring", "requiredStock": 3}, {"season": "summer", "requiredStock": 3}, {"season": "fall", "requiredStock": 3}]', '[]', NULL, 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-113', 'kitchen', '쿠킹호일', 'non-food', 'room-temp', '소모품', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '[]', NULL, 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-114', 'kitchen', '키친타올', 'non-food', 'room-temp', '소모품', '개', 7, 0, 2, 4, '[{"season": "winter", "requiredStock": 4}, {"season": "spring", "requiredStock": 4}, {"season": "summer", "requiredStock": 4}, {"season": "fall", "requiredStock": 4}]', '[]', NULL, 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-115', 'kitchen', '유니랩', 'non-food', 'room-temp', '소모품', '개', 1, 0, 2, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '[]', NULL, 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-117', 'kitchen', '주방세제', 'non-food', 'room-temp', '소모품', '개', 2, 0, 2, 2, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '[]', NULL, 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-116', 'kitchen', '부탄가스', 'non-food', 'room-temp', '소모품', '개', 2, 0, 2, 1, '[{"season": "winter", "requiredStock": 4}, {"season": "spring", "requiredStock": 4}, {"season": "summer", "requiredStock": 4}, {"season": "fall", "requiredStock": 4}]', '[]', NULL, 'ordered', 2, '2026-01-11T14:54:03.584Z', 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-118', 'kitchen', '식기세척기세제', 'non-food', 'room-temp', '소모품', '개', 0, 0, 3, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '[]', NULL, 'ordered', 1, '2026-01-11T14:54:05.028Z', 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-105', 'kitchen', '강력분', 'food', 'room-temp', '가루류', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k17"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-106', 'kitchen', '호밀가루', 'food', 'room-temp', '가루류', '개', 2, 0, 1, 2, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '["tag-k17"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-098', 'kitchen', '구운소금', 'food', 'room-temp', '가루류', '개', 4, 0, 2, 3, '[{"season": "winter", "requiredStock": 3}, {"season": "spring", "requiredStock": 3}, {"season": "summer", "requiredStock": 3}, {"season": "fall", "requiredStock": 3}]', '["tag-k6", "tag-k7", "tag-k8"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-023', 'kitchen', '전처리양파_채', 'food', 'refrigerated', '잎채소&허브류', '개', 4, 1, 2, 4, '[{"season": "winter", "requiredStock": 6}, {"season": "spring", "requiredStock": 6}, {"season": "summer", "requiredStock": 6}, {"season": "fall", "requiredStock": 6}]', '["tag-k14"]', '2026-01-12', 'ordered', 2, '2026-01-11T14:53:42.267Z', 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-037', 'kitchen', '바나나', 'food', 'refrigerated', '채소&버섯&과일', '개', 0, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k5"]', '2026-01-12', 'ordered', 1, '2026-01-11T14:53:44.484Z', NULL);
INSERT INTO public.inventory_items VALUES ('item-078', 'kitchen', '꿀', 'food', 'room-temp', '상온소스', '개', 2, 0, 2, 2, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '["tag-k2", "tag-k7"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-004', 'kitchen', '페코리노', 'food', 'refrigerated', '유제품&치즈', '개', 1, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k5"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-020', 'kitchen', '치커리', 'food', 'refrigerated', '잎채소&허브류', '개', 0.2, 0, 2, 0, '[{"season": "winter", "requiredStock": 0.2}, {"season": "spring", "requiredStock": 0.2}, {"season": "summer", "requiredStock": 0.2}, {"season": "fall", "requiredStock": 0.2}]', '["tag-k11"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-021', 'kitchen', '파세리', 'food', 'refrigerated', '잎채소&허브류', '개', 2, 0, 2, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k8", "tag-k15"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-062', 'kitchen', '링귀니', 'food', 'room-temp', '가공식품', '개', 8, 1.5, 1, 6, '[{"season": "winter", "requiredStock": 8}, {"season": "spring", "requiredStock": 8}, {"season": "summer", "requiredStock": 8}, {"season": "fall", "requiredStock": 8}]', '["tag-k3"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-073', 'kitchen', '발사믹', 'food', 'room-temp', '상온소스', '개', 5, 0.1, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k8"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-084', 'kitchen', '바질잎드', 'food', 'room-temp', '건허브&향신료', '개', 2, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k1"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-104', 'kitchen', '중력분', 'food', 'room-temp', '가루류', '개', 4, 0, 1, 1, '[{"season": "winter", "requiredStock": 1}, {"season": "spring", "requiredStock": 1}, {"season": "summer", "requiredStock": 1}, {"season": "fall", "requiredStock": 1}]', '["tag-k8"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('item-045', 'kitchen', '삼배체굴', 'food', 'refrigerated', '특수발주', '개', 3, 2, 1, 2, '[{"season": "winter", "requiredStock": 3}, {"season": "spring", "requiredStock": 3}, {"season": "summer", "requiredStock": 3}, {"season": "fall", "requiredStock": 3}]', '["tag-k16"]', '2026-01-12', 'normal', NULL, NULL, NULL);
INSERT INTO public.inventory_items VALUES ('02394944-9130-42d1-b5f7-e17aa5c61a3c', 'cafe', '아메리카노 원두', 'food', 'room-temp', '원두·커피', '개', 1, 0.5, 2, 5, '[{"season": "winter", "requiredStock": 3}, {"season": "spring", "requiredStock": 3}, {"season": "summer", "requiredStock": 3}, {"season": "fall", "requiredStock": 3}]', '[]', NULL, 'ordered', 2, '2026-01-11T15:17:24.976Z', 'sup-c5');
INSERT INTO public.inventory_items VALUES ('item-055', 'kitchen', '바게트', 'food', 'frozen', '냉동빵류', '개', 23, 1, 2, 2, '[{"season": "winter", "requiredStock": 4}, {"season": "spring", "requiredStock": 4}, {"season": "summer", "requiredStock": 4}, {"season": "fall", "requiredStock": 4}]', '["tag-k14", "tag-k13", "tag-k6"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k1');
INSERT INTO public.inventory_items VALUES ('item-080', 'kitchen', '피스타치오스프레드', 'food', 'room-temp', '상온소스', '개', 2, 0, 1, 1, '[{"season": "winter", "requiredStock": 2}, {"season": "spring", "requiredStock": 2}, {"season": "summer", "requiredStock": 2}, {"season": "fall", "requiredStock": 2}]', '["tag-k10"]', '2026-01-12', 'normal', NULL, NULL, 'sup-k4');


--
-- Data for Name: menu_tags; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.menu_tags VALUES ('tag-c1', 'cafe', '아메리카노', 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300');
INSERT INTO public.menu_tags VALUES ('tag-c2', 'cafe', '카페라떼', 'bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-300');
INSERT INTO public.menu_tags VALUES ('tag-c3', 'cafe', '바닐라라떼', 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-300');
INSERT INTO public.menu_tags VALUES ('tag-c4', 'cafe', '카푸치노', 'bg-lime-100 text-lime-700 dark:bg-lime-900/30 dark:text-lime-300');
INSERT INTO public.menu_tags VALUES ('tag-c5', 'cafe', '에스프레소', 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300');
INSERT INTO public.menu_tags VALUES ('tag-c6', 'cafe', '모카', 'bg-teal-100 text-teal-700 dark:bg-teal-900/30 dark:text-teal-300');
INSERT INTO public.menu_tags VALUES ('tag-k1', 'kitchen', '코티지파이', 'bg-rose-100 text-rose-700 dark:bg-rose-900/30 dark:text-rose-300');
INSERT INTO public.menu_tags VALUES ('tag-k2', 'kitchen', '까망베르치즈구이', 'bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-300');
INSERT INTO public.menu_tags VALUES ('tag-k3', 'kitchen', '올리브파스타', 'bg-lime-100 text-lime-700 dark:bg-lime-900/30 dark:text-lime-300');
INSERT INTO public.menu_tags VALUES ('tag-k5', 'kitchen', '프렌치토스트', 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-300');
INSERT INTO public.menu_tags VALUES ('tag-k6', 'kitchen', '토마토스프', 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-300');
INSERT INTO public.menu_tags VALUES ('tag-k7', 'kitchen', '꿀대구', 'bg-teal-100 text-teal-700 dark:bg-teal-900/30 dark:text-teal-300');
INSERT INTO public.menu_tags VALUES ('tag-k9', 'kitchen', '치즈팔레트', 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-300');
INSERT INTO public.menu_tags VALUES ('tag-k10', 'kitchen', '티라미슈', 'bg-pink-100 text-pink-700 dark:bg-pink-900/30 dark:text-pink-300');
INSERT INTO public.menu_tags VALUES ('tag-k11', 'kitchen', '샐러드', 'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-300');
INSERT INTO public.menu_tags VALUES ('tag-k12', 'kitchen', '브루기뇽', 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-300');
INSERT INTO public.menu_tags VALUES ('tag-k13', 'kitchen', '감바스', 'bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30 dark:text-cyan-300');
INSERT INTO public.menu_tags VALUES ('tag-k14', 'kitchen', '어니언스프', 'bg-fuchsia-100 text-fuchsia-700 dark:bg-fuchsia-900/30 dark:text-fuchsia-300');
INSERT INTO public.menu_tags VALUES ('tag-k15', 'kitchen', '트러플추가', 'bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-300');
INSERT INTO public.menu_tags VALUES ('tag-k17', 'kitchen', '수제바게트', 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-300');
INSERT INTO public.menu_tags VALUES ('tag-k8', 'kitchen', '뇨끼', 'bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-300');
INSERT INTO public.menu_tags VALUES ('tag-k16', 'kitchen', '오이스터', 'bg-sky-100 text-sky-700 dark:bg-sky-900/30 dark:text-sky-300');
INSERT INTO public.menu_tags VALUES ('tag-k4', 'kitchen', '잠봉파스타', 'bg-violet-100 text-violet-700 dark:bg-violet-900/30 dark:text-violet-300');


--
-- Data for Name: sub_categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.sub_categories VALUES ('subcat-k1', 'kitchen', 'food', '유제품&치즈');
INSERT INTO public.sub_categories VALUES ('subcat-k2', 'kitchen', 'food', '가공육류&알');
INSERT INTO public.sub_categories VALUES ('subcat-k3', 'kitchen', 'food', '잎채소&허브류');
INSERT INTO public.sub_categories VALUES ('subcat-k4', 'kitchen', 'food', '채소&버섯&과일');
INSERT INTO public.sub_categories VALUES ('subcat-k5', 'kitchen', 'food', '소스&절임류');
INSERT INTO public.sub_categories VALUES ('subcat-k6', 'kitchen', 'food', '특수발주');
INSERT INTO public.sub_categories VALUES ('subcat-k7', 'kitchen', 'food', '냉동유제품');
INSERT INTO public.sub_categories VALUES ('subcat-k8', 'kitchen', 'food', '냉동육류');
INSERT INTO public.sub_categories VALUES ('subcat-k9', 'kitchen', 'food', '냉동해산물');
INSERT INTO public.sub_categories VALUES ('subcat-k10', 'kitchen', 'food', '냉동빵류');
INSERT INTO public.sub_categories VALUES ('subcat-k11', 'kitchen', 'food', '냉동기타');
INSERT INTO public.sub_categories VALUES ('subcat-k12', 'kitchen', 'food', '상온채소');
INSERT INTO public.sub_categories VALUES ('subcat-k13', 'kitchen', 'food', '가공식품');
INSERT INTO public.sub_categories VALUES ('subcat-k14', 'kitchen', 'food', '오일');
INSERT INTO public.sub_categories VALUES ('subcat-k15', 'kitchen', 'food', '캔');
INSERT INTO public.sub_categories VALUES ('subcat-k16', 'kitchen', 'food', '상온소스');
INSERT INTO public.sub_categories VALUES ('subcat-k17', 'kitchen', 'food', '건허브&향신료');
INSERT INTO public.sub_categories VALUES ('subcat-k18', 'kitchen', 'food', '견과류&곡물류');
INSERT INTO public.sub_categories VALUES ('subcat-k19', 'kitchen', 'food', '가루류');
INSERT INTO public.sub_categories VALUES ('subcat-k20', 'kitchen', 'non-food', '소모품');
INSERT INTO public.sub_categories VALUES ('subcat-c1', 'cafe', 'food', '원두·커피');
INSERT INTO public.sub_categories VALUES ('subcat-c2', 'cafe', 'food', '시럽·소스');
INSERT INTO public.sub_categories VALUES ('subcat-c3', 'cafe', 'non-food', '소모품');


--
-- Data for Name: suppliers; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.suppliers VALUES ('sup-k1', 'kitchen', '도레미', NULL);
INSERT INTO public.suppliers VALUES ('sup-k2', 'kitchen', '쿠팡', 'https://www.coupang.com');
INSERT INTO public.suppliers VALUES ('sup-k3', 'kitchen', '그린팜', NULL);
INSERT INTO public.suppliers VALUES ('sup-k4', 'kitchen', '네이버', 'https://shopping.naver.com');
INSERT INTO public.suppliers VALUES ('sup-k5', 'kitchen', '기타', NULL);
INSERT INTO public.suppliers VALUES ('sup-c1', 'cafe', '도레미', NULL);
INSERT INTO public.suppliers VALUES ('sup-c2', 'cafe', '쿠팡', 'https://www.coupang.com');
INSERT INTO public.suppliers VALUES ('sup-c3', 'cafe', '그린팜', NULL);
INSERT INTO public.suppliers VALUES ('sup-c4', 'cafe', '네이버', 'https://shopping.naver.com');
INSERT INTO public.suppliers VALUES ('sup-c5', 'cafe', '기타', NULL);


--
-- PostgreSQL database dump complete
--

\unrestrict mE1ibhHNwwgxE2hSGmXcCjcSF9pwYa65KWaQzOVUz6QjKOcsgYUaRcajJjXDFLF

