-- ==============================================
-- 프로덕션 데이터베이스 동기화 스크립트
-- 개발 DB -> 프로덕션 DB 데이터 이관용
-- 생성일: 2026-01-13
-- 
-- 사용법:
-- 1. Replit Database 탭 -> Production 선택
-- 2. My Data 탭 -> SQL runner (또는 콘솔)
-- 3. 이 스크립트 전체를 붙여넣고 실행
-- ==============================================

-- 기존 데이터 삭제 (순서 중요)
DELETE FROM item_orders;
DELETE FROM inventory_items;
DELETE FROM menu_tags;
DELETE FROM sub_categories;
DELETE FROM suppliers;

-- ==============================================
-- 1. SUPPLIERS (공급업체)
-- ==============================================
INSERT INTO suppliers (id, team, name, url) VALUES ('sup-c1', 'cafe', '도레미', NULL);
INSERT INTO suppliers (id, team, name, url) VALUES ('sup-c2', 'cafe', '쿠팡', 'https://www.coupang.com');
INSERT INTO suppliers (id, team, name, url) VALUES ('sup-c3', 'cafe', '그린팜', NULL);
INSERT INTO suppliers (id, team, name, url) VALUES ('sup-c4', 'cafe', '네이버', 'https://shopping.naver.com');
INSERT INTO suppliers (id, team, name, url) VALUES ('sup-c5', 'cafe', '기타', NULL);
INSERT INTO suppliers (id, team, name, url) VALUES ('sup-k1', 'kitchen', '도레미', NULL);
INSERT INTO suppliers (id, team, name, url) VALUES ('sup-k2', 'kitchen', '쿠팡', 'https://www.coupang.com');
INSERT INTO suppliers (id, team, name, url) VALUES ('sup-k3', 'kitchen', '그린팜', NULL);
INSERT INTO suppliers (id, team, name, url) VALUES ('sup-k4', 'kitchen', '네이버', 'https://shopping.naver.com');
INSERT INTO suppliers (id, team, name, url) VALUES ('sup-k5', 'kitchen', '기타', NULL);

-- ==============================================
-- 2. MENU_TAGS (메뉴 태그)
-- ==============================================
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-c1', 'cafe', '아메리카노', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-c2', 'cafe', '카페라떼', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-c3', 'cafe', '바닐라라떼', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-c4', 'cafe', '카푸치노', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-c5', 'cafe', '에스프레소', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-c6', 'cafe', '모카', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-k1', 'kitchen', '코티지파이', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-k10', 'kitchen', '티라미슈', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-k11', 'kitchen', '샐러드', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-k12', 'kitchen', '브루기뇽', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-k13', 'kitchen', '감바스', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-k14', 'kitchen', '어니언스프', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-k15', 'kitchen', '트러플추가', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-k16', 'kitchen', '오이스터', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-k17', 'kitchen', '수제바게트', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-k2', 'kitchen', '까망베르치즈구이', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-k3', 'kitchen', '올리브파스타', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-k4', 'kitchen', '잠봉파스타', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-k5', 'kitchen', '프렌치토스트', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-k6', 'kitchen', '토마토스프', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-k7', 'kitchen', '꿀대구', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-k8', 'kitchen', '뇨끼', NULL);
INSERT INTO menu_tags (id, team, name, color) VALUES ('tag-k9', 'kitchen', '치즈팔레트', NULL);

-- ==============================================
-- 3. SUB_CATEGORIES (소분류)
-- ==============================================
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-c1', 'cafe', 'food', '원두·커피');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-c2', 'cafe', 'food', '시럽·소스');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-c3', 'cafe', 'non-food', '소모품');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-k1', 'kitchen', 'food', '유제품&치즈');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-k10', 'kitchen', 'food', '냉동빵류');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-k11', 'kitchen', 'food', '냉동기타');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-k12', 'kitchen', 'food', '상온채소');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-k13', 'kitchen', 'food', '가공식품');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-k14', 'kitchen', 'food', '오일');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-k15', 'kitchen', 'food', '캔');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-k16', 'kitchen', 'food', '상온소스');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-k17', 'kitchen', 'food', '건허브&향신료');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-k18', 'kitchen', 'food', '견과류&곡물류');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-k19', 'kitchen', 'food', '가루류');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-k2', 'kitchen', 'food', '가공육류&알');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-k20', 'kitchen', 'non-food', '소모품');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-k3', 'kitchen', 'food', '잎채소&허브류');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-k4', 'kitchen', 'food', '채소&버섯&과일');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-k5', 'kitchen', 'food', '소스&절임류');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-k6', 'kitchen', 'food', '특수발주');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-k7', 'kitchen', 'food', '냉동유제품');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-k8', 'kitchen', 'food', '냉동육류');
INSERT INTO sub_categories (id, team, main_category, name) VALUES ('subcat-k9', 'kitchen', 'food', '냉동해산물');

-- ==============================================
-- 4. INVENTORY_ITEMS (재고 품목)
-- ==============================================
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('02394944-9130-42d1-b5f7-e17aa5c61a3c', 'cafe', '아메리카노 원두', 'food', 'room-temp', '원두·커피', '개', 1, 0.5, 2, 5, '[{"season":"winter","requiredStock":3},{"season":"spring","requiredStock":3},{"season":"summer","requiredStock":3},{"season":"fall","requiredStock":3}]'::jsonb, '[]'::jsonb, NULL, 'ordered', 2, '2026-01-11T15:17:24.976Z', 'sup-c5', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('0655d4eb-698a-410d-9a33-af3b65c7330e', 'kitchen', '.전처리양파_쵸핑', 'food', 'refrigerated', '채소&버섯&과일', '개', 10, 0, 2, 10, '[{"season":"winter","leadTime":2,"dailyUsage":0,"safetyStock":10,"requiredStock":10},{"season":"spring","leadTime":2,"dailyUsage":0,"safetyStock":10,"requiredStock":10},{"season":"summer","leadTime":2,"dailyUsage":0,"safetyStock":10,"requiredStock":10},{"season":"fall","leadTime":2,"dailyUsage":0,"safetyStock":10,"requiredStock":10}]'::jsonb, '["tag-k1"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('65b02895-2f2f-4925-bc5b-efcd02545728', 'kitchen', '0.깐마늘', 'food', 'refrigerated', '채소&버섯&과일', '개', 1, 0.1, 1, 1, '[{"season":"winter","leadTime":1,"dailyUsage":0.1,"safetyStock":0.5,"requiredStock":1},{"season":"spring","leadTime":1,"dailyUsage":0.1,"safetyStock":1,"requiredStock":1},{"season":"summer","leadTime":1,"dailyUsage":0.1,"safetyStock":1,"requiredStock":1},{"season":"fall","leadTime":1,"dailyUsage":0.1,"safetyStock":1,"requiredStock":1}]'::jsonb, '["tag-k7"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('68892ed8-7814-4f66-840c-54c5c8a93914', 'kitchen', '.전처리양파_채', 'food', 'refrigerated', '채소&버섯&과일', '개', 6, 1, 2, 4, '[{"season":"winter","leadTime":2,"dailyUsage":1,"safetyStock":4,"requiredStock":6},{"season":"spring","leadTime":2,"dailyUsage":1,"safetyStock":4,"requiredStock":6},{"season":"summer","leadTime":2,"dailyUsage":1,"safetyStock":4,"requiredStock":6},{"season":"fall","leadTime":2,"dailyUsage":1,"safetyStock":4,"requiredStock":6}]'::jsonb, '["tag-k14"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('80ab2f0a-d479-450b-8e4f-8a9594b2e82c', 'kitchen', '토마토', 'food', 'refrigerated', '채소&버섯&과일', '개', 4, 0, 1, 1, '[{"season":"winter","leadTime":1,"dailyUsage":0,"safetyStock":1,"requiredStock":1},{"season":"spring","leadTime":1,"dailyUsage":0,"safetyStock":1,"requiredStock":1},{"season":"summer","leadTime":1,"dailyUsage":0,"safetyStock":1,"requiredStock":1},{"season":"fall","leadTime":1,"dailyUsage":0,"safetyStock":1,"requiredStock":1}]'::jsonb, '["tag-k7","tag-k6"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('a446276e-85a3-4406-a415-3b5b0c8b5d17', 'kitchen', '살라미', 'food', 'refrigerated', '가공육류&알', '개', 3, 0, 2, 2, '[{"season":"winter","leadTime":2,"dailyUsage":0,"safetyStock":2,"requiredStock":0},{"season":"spring","leadTime":2,"dailyUsage":0,"safetyStock":2,"requiredStock":0},{"season":"summer","leadTime":2,"dailyUsage":0,"safetyStock":2,"requiredStock":0},{"season":"fall","leadTime":2,"dailyUsage":0,"safetyStock":2,"requiredStock":0}]'::jsonb, '["tag-k9"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('b77b5f14-7803-4f9b-a694-aee87b6ea895', 'kitchen', '블랙올리브', 'food', 'room-temp', '캔', '개', 4, 1, 1, 3, '[{"season":"winter","leadTime":1,"dailyUsage":1,"safetyStock":3,"requiredStock":4},{"season":"spring","leadTime":1,"dailyUsage":1,"safetyStock":3,"requiredStock":4},{"season":"summer","leadTime":1,"dailyUsage":1,"safetyStock":3,"requiredStock":4},{"season":"fall","leadTime":1,"dailyUsage":1,"safetyStock":3,"requiredStock":4}]'::jsonb, '["tag-k3","tag-k6","tag-k11"]'::jsonb, NULL, 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('cd272c2d-1f25-4530-8a52-e1d0122144fe', 'kitchen', '.깐양파', 'food', 'refrigerated', '채소&버섯&과일', '개', 2, 0, 2, 2, '[{"season":"winter","leadTime":2,"dailyUsage":0,"safetyStock":2,"requiredStock":2},{"season":"spring","leadTime":2,"dailyUsage":0,"safetyStock":2,"requiredStock":2},{"season":"summer","leadTime":2,"dailyUsage":0,"safetyStock":2,"requiredStock":2},{"season":"fall","leadTime":2,"dailyUsage":0,"safetyStock":2,"requiredStock":2}]'::jsonb, '["tag-k12"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('d72a37a8-c71e-42a8-9f27-1059f27d7ef8', 'kitchen', '파프리카', 'food', 'refrigerated', '채소&버섯&과일', '개', 1, 0, 1, 1, '[{"season":"winter","leadTime":1,"dailyUsage":0,"safetyStock":1,"requiredStock":1},{"season":"spring","leadTime":1,"dailyUsage":0,"safetyStock":1,"requiredStock":1},{"season":"summer","leadTime":1,"dailyUsage":0,"safetyStock":1,"requiredStock":1},{"season":"fall","leadTime":1,"dailyUsage":0,"safetyStock":1,"requiredStock":1}]'::jsonb, '["tag-k7"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('ebbd1f02-4427-4377-858f-dd63fb29527b', 'kitchen', '방울토마토', 'food', 'refrigerated', '채소&버섯&과일', '개', 3, 1, 1, 2, '[{"season":"winter","leadTime":1,"dailyUsage":1,"safetyStock":2,"requiredStock":3},{"season":"spring","leadTime":1,"dailyUsage":1,"safetyStock":2,"requiredStock":3},{"season":"summer","leadTime":1,"dailyUsage":1,"safetyStock":2,"requiredStock":3},{"season":"fall","leadTime":1,"dailyUsage":1,"safetyStock":2,"requiredStock":3}]'::jsonb, '["tag-k8","tag-k11","tag-k13"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-001', 'kitchen', '슬라이스 치즈', 'food', 'refrigerated', '유제품&치즈', '개', 1, 0.1, 1, 20, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k1"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-002', 'kitchen', '까망베르 치즈', 'food', 'refrigerated', '유제품&치즈', '개', 12, 2, 1, 10, '[{"season":"winter","requiredStock":12},{"season":"spring","requiredStock":12},{"season":"summer","requiredStock":12},{"season":"fall","requiredStock":12}]'::jsonb, '["tag-k2"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-003', 'kitchen', '그라나파다노', 'food', 'refrigerated', '유제품&치즈', '개', 3, 0, 1, 3, '[{"season":"winter","requiredStock":3},{"season":"spring","requiredStock":3},{"season":"summer","requiredStock":3},{"season":"fall","requiredStock":3}]'::jsonb, '["tag-k3","tag-k4","tag-k8"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-004', 'kitchen', '페코리노', 'food', 'refrigerated', '유제품&치즈', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k5"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-005', 'kitchen', '난황', 'food', 'refrigerated', '유제품&치즈', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k10","tag-k5"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-006', 'kitchen', '우유', 'food', 'refrigerated', '유제품&치즈', '개', 3, 1, 1, 2, '[{"season":"winter","requiredStock":3},{"season":"spring","requiredStock":3},{"season":"summer","requiredStock":3},{"season":"fall","requiredStock":3}]'::jsonb, '["tag-k1","tag-k8"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-007', 'kitchen', '생크림', 'food', 'refrigerated', '유제품&치즈', '개', 29, 3, 1, 10, '[{"season":"winter","requiredStock":13},{"season":"spring","requiredStock":13},{"season":"summer","requiredStock":13},{"season":"fall","requiredStock":13}]'::jsonb, '["tag-k4","tag-k5","tag-k10"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-008', 'kitchen', '비건생크림', 'food', 'refrigerated', '유제품&치즈', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k6"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k2', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-009', 'kitchen', '마가린', 'food', 'refrigerated', '유제품&치즈', '개', 2, 0, 1, 1, '[{"season":"winter","leadTime":1,"dailyUsage":0,"safetyStock":2,"requiredStock":2},{"season":"spring","leadTime":1,"dailyUsage":0,"safetyStock":1,"requiredStock":1},{"season":"summer","leadTime":1,"dailyUsage":0,"safetyStock":1,"requiredStock":1},{"season":"fall","leadTime":1,"dailyUsage":0,"safetyStock":1,"requiredStock":1}]'::jsonb, '["tag-k6"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-010', 'kitchen', '마스카포네치즈', 'food', 'refrigerated', '유제품&치즈', '개', 21, 2, 1, 6, '[{"season":"winter","requiredStock":8},{"season":"spring","requiredStock":8},{"season":"summer","requiredStock":8},{"season":"fall","requiredStock":8}]'::jsonb, '["tag-k10"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-011', 'kitchen', '과일치즈', 'food', 'refrigerated', '유제품&치즈', '개', 3, 0, 1, 2, '[{"season":"winter","leadTime":1,"dailyUsage":0,"safetyStock":1,"requiredStock":1},{"season":"spring","leadTime":1,"dailyUsage":0,"safetyStock":2,"requiredStock":2},{"season":"summer","leadTime":1,"dailyUsage":0,"safetyStock":2,"requiredStock":2},{"season":"fall","leadTime":1,"dailyUsage":0,"safetyStock":2,"requiredStock":2}]'::jsonb, '["tag-k9"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-012', 'kitchen', '스모크치즈', 'food', 'refrigerated', '유제품&치즈', '개', 1, 0, 2, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k9"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-013', 'kitchen', '크림치즈', 'food', 'refrigerated', '유제품&치즈', '개', 5, 0, 1, 3, '[{"season":"winter","requiredStock":3},{"season":"spring","requiredStock":3},{"season":"summer","requiredStock":3},{"season":"fall","requiredStock":3}]'::jsonb, '["tag-k9"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-014', 'kitchen', '살라미', 'food', 'refrigerated', '유제품&치즈', '개', 2, 0, 1, 2, '[{"season":"winter","requiredStock":2},{"season":"spring","requiredStock":2},{"season":"summer","requiredStock":2},{"season":"fall","requiredStock":2}]'::jsonb, '["tag-k9"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-015', 'kitchen', '하몽', 'food', 'refrigerated', '가공육류&알', '개', 2, 0, 1, 2, '[{"season":"winter","leadTime":1,"dailyUsage":0,"safetyStock":1,"requiredStock":1},{"season":"spring","leadTime":1,"dailyUsage":0,"safetyStock":2,"requiredStock":4},{"season":"summer","leadTime":1,"dailyUsage":0,"safetyStock":2,"requiredStock":2},{"season":"fall","leadTime":1,"dailyUsage":0,"safetyStock":2,"requiredStock":2}]'::jsonb, '["tag-k9"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-016', 'kitchen', '달걀', 'food', 'refrigerated', '가공육류&알', '개', 2, 0, 1, 1, '[{"season":"winter","leadTime":1,"dailyUsage":0,"safetyStock":1,"requiredStock":1},{"season":"spring","leadTime":1,"dailyUsage":0,"safetyStock":1,"requiredStock":1},{"season":"summer","leadTime":1,"dailyUsage":0,"safetyStock":1,"requiredStock":1},{"season":"fall","leadTime":1,"dailyUsage":0,"safetyStock":1,"requiredStock":4}]'::jsonb, '["tag-k5","tag-k8"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-017', 'kitchen', '딜', 'food', 'refrigerated', '잎채소&허브류', 'g', 100, 20, 50, 90, '[{"season":"winter","leadTime":2,"dailyUsage":20,"safetyStock":50,"requiredStock":90},{"season":"spring","leadTime":50,"dailyUsage":20,"safetyStock":90,"requiredStock":100},{"season":"summer","leadTime":50,"dailyUsage":20,"safetyStock":90,"requiredStock":100},{"season":"fall","leadTime":50,"dailyUsage":20,"safetyStock":90,"requiredStock":100}]'::jsonb, '["tag-k3","tag-k2","tag-k11"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k3', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-018', 'kitchen', '처빌', 'food', 'refrigerated', '잎채소&허브류', '개', 2, 0, 2, 0, '[{"season":"winter","leadTime":2,"dailyUsage":0,"safetyStock":2,"requiredStock":2},{"season":"spring","leadTime":2,"dailyUsage":0,"safetyStock":0,"requiredStock":2},{"season":"summer","leadTime":2,"dailyUsage":0,"safetyStock":0,"requiredStock":2},{"season":"fall","leadTime":2,"dailyUsage":0,"safetyStock":0,"requiredStock":2}]'::jsonb, '["tag-k6","tag-k11","tag-k16"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k3', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-019', 'kitchen', '어린잎250g', 'food', 'refrigerated', '잎채소&허브류', '개', 2, 0.3, 2, 1, '[{"season":"winter","requiredStock":2},{"season":"spring","requiredStock":2},{"season":"summer","requiredStock":2},{"season":"fall","requiredStock":2}]'::jsonb, '["tag-k11"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-020', 'kitchen', '치커리', 'food', 'refrigerated', '잎채소&허브류', '개', 0.2, 0, 2, 0, '[{"season":"winter","leadTime":2,"dailyUsage":0,"safetyStock":0.1,"requiredStock":0.2},{"season":"spring","leadTime":2,"dailyUsage":0,"safetyStock":0,"requiredStock":0.2},{"season":"summer","leadTime":2,"dailyUsage":0,"safetyStock":0,"requiredStock":0.2},{"season":"fall","leadTime":2,"dailyUsage":0,"safetyStock":0,"requiredStock":0.2}]'::jsonb, '["tag-k11"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-021', 'kitchen', '파세리', 'food', 'refrigerated', '잎채소&허브류', '개', 2, 0, 2, 1, '[{"season":"winter","leadTime":2,"dailyUsage":0,"safetyStock":0.5,"requiredStock":1},{"season":"spring","leadTime":2,"dailyUsage":0,"safetyStock":1,"requiredStock":1},{"season":"summer","leadTime":2,"dailyUsage":0,"safetyStock":1,"requiredStock":1},{"season":"fall","leadTime":2,"dailyUsage":0,"safetyStock":1,"requiredStock":1}]'::jsonb, '["tag-k8","tag-k12"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-022', 'kitchen', '타임', 'food', 'refrigerated', '잎채소&허브류', '개', 3, 0.5, 2, 2, '[{"season":"winter","requiredStock":3},{"season":"spring","requiredStock":3},{"season":"summer","requiredStock":3},{"season":"fall","requiredStock":3}]'::jsonb, '["tag-k12"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k3', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-030', 'kitchen', '0.깐편마늘', 'food', 'refrigerated', '채소&버섯&과일', '개', 4, 1, 2, 2, '[{"season":"winter","requiredStock":4},{"season":"spring","requiredStock":4},{"season":"summer","requiredStock":4},{"season":"fall","requiredStock":4}]'::jsonb, '["tag-k13"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-031', 'kitchen', '꽈리고추', 'food', 'refrigerated', '채소&버섯&과일', '개', 0.2, 0, 1, 0, '[{"season":"winter","leadTime":1,"dailyUsage":0,"safetyStock":0.1,"requiredStock":0.1},{"season":"spring","leadTime":1,"dailyUsage":0,"safetyStock":0,"requiredStock":0.1},{"season":"summer","leadTime":1,"dailyUsage":0,"safetyStock":0,"requiredStock":0.1},{"season":"fall","leadTime":1,"dailyUsage":0,"safetyStock":0,"requiredStock":0.1}]'::jsonb, '["tag-k13"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-032', 'kitchen', '양송이', 'food', 'refrigerated', '채소&버섯&과일', '개', 3, 1, 1, 2, '[{"season":"winter","requiredStock":3},{"season":"spring","requiredStock":3},{"season":"summer","requiredStock":3},{"season":"fall","requiredStock":3}]'::jsonb, '["tag-k4","tag-k3","tag-k13"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-033', 'kitchen', '당근', 'food', 'refrigerated', '채소&버섯&과일', '개', 3, 0.5, 1, 1, '[{"season":"winter","leadTime":1,"dailyUsage":1,"safetyStock":2,"requiredStock":3},{"season":"spring","leadTime":1,"dailyUsage":0.5,"safetyStock":1,"requiredStock":2},{"season":"summer","leadTime":1,"dailyUsage":0.5,"safetyStock":1,"requiredStock":2},{"season":"fall","leadTime":1,"dailyUsage":0.5,"safetyStock":1,"requiredStock":2}]'::jsonb, '["tag-k12"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-034', 'kitchen', '샐러리', 'food', 'refrigerated', '채소&버섯&과일', '개', 2, 0.5, 1, 1, '[{"season":"winter","requiredStock":2},{"season":"spring","requiredStock":2},{"season":"summer","requiredStock":2},{"season":"fall","requiredStock":2}]'::jsonb, '["tag-k12"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-035', 'kitchen', '레몬', 'food', 'refrigerated', '채소&버섯&과일', '개', 30, 5, 2, 10, '[{"season":"winter","requiredStock":20},{"season":"spring","requiredStock":20},{"season":"summer","requiredStock":20},{"season":"fall","requiredStock":20}]'::jsonb, '["tag-k3","tag-k2"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k3', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-036', 'kitchen', '청포도or샤인머스캣', 'food', 'refrigerated', '채소&버섯&과일', '개', 3, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k5","tag-k9"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k2', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-037', 'kitchen', '바나나', 'food', 'refrigerated', '채소&버섯&과일', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k5"]'::jsonb, '2026-01-14', 'ordered', 1, '2026-01-11T14:53:44.484Z', 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-038', 'kitchen', '마요네즈', 'food', 'refrigerated', '소스&절임류', '개', 1, 0, 2, 1, '[{"season":"winter","leadTime":1,"dailyUsage":0,"safetyStock":1,"requiredStock":1},{"season":"spring","leadTime":2,"dailyUsage":0,"safetyStock":1,"requiredStock":1},{"season":"summer","leadTime":2,"dailyUsage":0,"safetyStock":1,"requiredStock":1},{"season":"fall","leadTime":2,"dailyUsage":0,"safetyStock":1,"requiredStock":1}]'::jsonb, '["tag-k7"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-039', 'kitchen', '라임주스', 'food', 'refrigerated', '소스&절임류', '개', 1, 0, 2, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k8"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-040', 'kitchen', '카스텔베트라노', 'food', 'refrigerated', '소스&절임류', '개', 10, 1, 2, 4, '[{"season":"winter","leadTime":1,"dailyUsage":0.2,"safetyStock":2,"requiredStock":2},{"season":"spring","leadTime":2,"dailyUsage":1,"safetyStock":4,"requiredStock":6},{"season":"summer","leadTime":2,"dailyUsage":1,"safetyStock":4,"requiredStock":6},{"season":"fall","leadTime":2,"dailyUsage":1,"safetyStock":4,"requiredStock":6}]'::jsonb, '["tag-k9"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-041', 'kitchen', '아르티지아나트러플소스', 'food', 'refrigerated', '소스&절임류', '개', 7, 1, 2, 4, '[{"season":"winter","requiredStock":6},{"season":"spring","requiredStock":6},{"season":"summer","requiredStock":6},{"season":"fall","requiredStock":6}]'::jsonb, '["tag-k15"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k4', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-042', 'kitchen', '굴소스', 'food', 'refrigerated', '소스&절임류', '개', 2, 0, 1, 2, '[{"season":"winter","requiredStock":2},{"season":"spring","requiredStock":2},{"season":"summer","requiredStock":2},{"season":"fall","requiredStock":2}]'::jsonb, '["tag-k1"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-043', 'kitchen', '케이퍼', 'food', 'refrigerated', '소스&절임류', '개', 2, 0.1, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k11"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-044', 'kitchen', '앤초비', 'food', 'refrigerated', '소스&절임류', '개', 1, 0.1, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k13"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-045', 'kitchen', '삼배체굴', 'food', 'refrigerated', '특수발주', '개', 10, 2, 1, 2, '[{"season":"winter","leadTime":2,"dailyUsage":0.5,"safetyStock":1,"requiredStock":2},{"season":"spring","leadTime":1,"dailyUsage":2,"safetyStock":2,"requiredStock":3},{"season":"summer","leadTime":1,"dailyUsage":2,"safetyStock":2,"requiredStock":3},{"season":"fall","leadTime":1,"dailyUsage":2,"safetyStock":2,"requiredStock":3}]'::jsonb, '["tag-k16"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-046', 'kitchen', '생트러플', 'food', 'refrigerated', '특수발주', '개', 50, 0, 2, 1, '[{"season":"winter","leadTime":1,"dailyUsage":0.2,"safetyStock":50,"requiredStock":50},{"season":"spring","leadTime":2,"dailyUsage":0,"safetyStock":1,"requiredStock":50},{"season":"summer","leadTime":2,"dailyUsage":0,"safetyStock":1,"requiredStock":50},{"season":"fall","leadTime":2,"dailyUsage":0,"safetyStock":1,"requiredStock":50}]'::jsonb, '["tag-k15"]'::jsonb, '2026-01-14', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-047', 'kitchen', '모짜렐라', 'food', 'frozen', '냉동유제품', '개', 4, 0.5, 3, 4, '[{"season":"winter","leadTime":3,"dailyUsage":0.5,"safetyStock":3,"requiredStock":4},{"season":"spring","leadTime":3,"dailyUsage":0.5,"safetyStock":4,"requiredStock":4},{"season":"summer","leadTime":3,"dailyUsage":0.5,"safetyStock":4,"requiredStock":4},{"season":"fall","leadTime":3,"dailyUsage":0.5,"safetyStock":4,"requiredStock":4}]'::jsonb, '["tag-k1"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-048', 'kitchen', '버터', 'food', 'frozen', '냉동유제품', '개', 19, 4, 1, 15, '[{"season":"winter","requiredStock":19},{"season":"spring","requiredStock":19},{"season":"summer","requiredStock":19},{"season":"fall","requiredStock":19}]'::jsonb, '["tag-k1","tag-k3","tag-k5","tag-k8","tag-k14"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-049', 'kitchen', '베이컨', 'food', 'frozen', '냉동육류', '개', 11, 1, 2, 6, '[{"season":"winter","requiredStock":8},{"season":"spring","requiredStock":8},{"season":"summer","requiredStock":8},{"season":"fall","requiredStock":8}]'::jsonb, '["tag-k3","tag-k5"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-050', 'kitchen', '잠봉', 'food', 'frozen', '냉동육류', '개', 7, 1, 2, 5, '[{"season":"winter","leadTime":1,"dailyUsage":1,"safetyStock":5,"requiredStock":6},{"season":"spring","leadTime":2,"dailyUsage":1,"safetyStock":5,"requiredStock":6},{"season":"summer","leadTime":2,"dailyUsage":1,"safetyStock":5,"requiredStock":6},{"season":"fall","leadTime":2,"dailyUsage":1,"safetyStock":5,"requiredStock":6}]'::jsonb, '["tag-k4","tag-k9"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-051', 'kitchen', '.우민찌', 'food', 'frozen', '냉동육류', '개', 16, 2, 2, 6, '[{"season":"winter","requiredStock":10},{"season":"spring","requiredStock":10},{"season":"summer","requiredStock":10},{"season":"fall","requiredStock":10}]'::jsonb, '["tag-k1"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-052', 'kitchen', '.돈민찌', 'food', 'frozen', '냉동육류', '개', 16, 0, 2, 1, '[{"season":"winter","leadTime":2,"dailyUsage":2,"safetyStock":6,"requiredStock":10},{"season":"spring","leadTime":2,"dailyUsage":0,"safetyStock":1,"requiredStock":1},{"season":"summer","leadTime":2,"dailyUsage":0,"safetyStock":1,"requiredStock":1},{"season":"fall","leadTime":2,"dailyUsage":0,"safetyStock":1,"requiredStock":1}]'::jsonb, '["tag-k1"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-053', 'kitchen', '새우', 'food', 'frozen', '냉동해산물', '개', 3, 0.5, 1, 3, '[{"season":"winter","leadTime":1,"dailyUsage":0.5,"safetyStock":2,"requiredStock":3},{"season":"spring","leadTime":1,"dailyUsage":0.5,"safetyStock":3,"requiredStock":3},{"season":"summer","leadTime":1,"dailyUsage":0.5,"safetyStock":3,"requiredStock":3},{"season":"fall","leadTime":1,"dailyUsage":0.5,"safetyStock":3,"requiredStock":3}]'::jsonb, '["tag-k13","tag-k3"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-054', 'kitchen', '연어', 'food', 'frozen', '냉동해산물', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k11"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-055', 'kitchen', '바게트', 'food', 'frozen', '냉동빵류', '개', 8, 1, 2, 2, '[{"season":"winter","requiredStock":4},{"season":"spring","requiredStock":4},{"season":"summer","requiredStock":4},{"season":"fall","requiredStock":4}]'::jsonb, '["tag-k14","tag-k13","tag-k6"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-056', 'kitchen', '브리오슈', 'food', 'frozen', '냉동빵류', '개', 2, 1, 1, 1, '[{"season":"winter","requiredStock":2},{"season":"spring","requiredStock":2},{"season":"summer","requiredStock":2},{"season":"fall","requiredStock":2}]'::jsonb, '["tag-k5"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k2', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-057', 'kitchen', '냉동브로콜리', 'food', 'frozen', '냉동기타', '개', 7, 1, 1, 3, '[{"season":"winter","requiredStock":4},{"season":"spring","requiredStock":4},{"season":"summer","requiredStock":4},{"season":"fall","requiredStock":4}]'::jsonb, '["tag-k13","tag-k12"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-058', 'kitchen', '메쉬드', 'food', 'frozen', '냉동기타', '개', 4, 1, 1, 3, '[{"season":"winter","requiredStock":4},{"season":"spring","requiredStock":4},{"season":"summer","requiredStock":4},{"season":"fall","requiredStock":4}]'::jsonb, '["tag-k1"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-059', 'kitchen', '라즈베리', 'food', 'frozen', '냉동기타', '개', 2, 0, 1, 2, '[{"season":"winter","requiredStock":2},{"season":"spring","requiredStock":2},{"season":"summer","requiredStock":2},{"season":"fall","requiredStock":2}]'::jsonb, '["tag-k5","tag-k9"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-060', 'kitchen', '샬롯', 'food', 'room-temp', '상온채소', '개', 3000, 50, 2, 500, '[{"season":"winter","requiredStock":600},{"season":"spring","requiredStock":600},{"season":"summer","requiredStock":600},{"season":"fall","requiredStock":600}]'::jsonb, '["tag-k8","tag-k16"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k3', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-061', 'kitchen', '크래커', 'food', 'room-temp', '가공식품', '개', 5, 0.1, 1, 3, '[{"season":"winter","leadTime":2,"dailyUsage":0.1,"safetyStock":3,"requiredStock":3},{"season":"spring","leadTime":1,"dailyUsage":0.1,"safetyStock":3,"requiredStock":5},{"season":"summer","leadTime":1,"dailyUsage":0.1,"safetyStock":3,"requiredStock":3},{"season":"fall","leadTime":1,"dailyUsage":0.1,"safetyStock":3,"requiredStock":3}]'::jsonb, '["tag-k2","tag-k9"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-062', 'kitchen', '링귀니', 'food', 'room-temp', '가공식품', '개', 8, 1.5, 1, 6, '[{"season":"winter","leadTime":1,"dailyUsage":1.5,"safetyStock":6,"requiredStock":8},{"season":"spring","leadTime":1,"dailyUsage":1.5,"safetyStock":6,"requiredStock":8},{"season":"summer","leadTime":1,"dailyUsage":1.5,"safetyStock":6,"requiredStock":8},{"season":"fall","leadTime":1,"dailyUsage":1.5,"safetyStock":6,"requiredStock":8}]'::jsonb, '["tag-k3"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-063', 'kitchen', '리가토니', 'food', 'room-temp', '가공식품', '개', 10, 2, 1, 8, '[{"season":"winter","requiredStock":10},{"season":"spring","requiredStock":10},{"season":"summer","requiredStock":10},{"season":"fall","requiredStock":10}]'::jsonb, '["tag-k4"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-064', 'kitchen', '사보이아르디', 'food', 'room-temp', '가공식품', '개', 8, 0.5, 1, 2, '[{"season":"winter","requiredStock":3},{"season":"spring","requiredStock":3},{"season":"summer","requiredStock":3},{"season":"fall","requiredStock":3}]'::jsonb, '["tag-k10"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-065', 'kitchen', '포마스', 'food', 'room-temp', '오일', '개', 2, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k5","tag-k8","tag-k15","tag-k13","tag-k3","tag-k12"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-066', 'kitchen', '엑스트라버진', 'food', 'room-temp', '오일', '개', 2, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k6","tag-k7","tag-k9","tag-k11","tag-k4","tag-k12"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-068', 'kitchen', '할라피뇨', 'food', 'room-temp', '캔', '개', 3, 0, 1, 0, '[{"season":"winter","leadTime":1,"dailyUsage":0,"safetyStock":2,"requiredStock":2},{"season":"spring","leadTime":1,"dailyUsage":0,"safetyStock":0,"requiredStock":2},{"season":"summer","leadTime":1,"dailyUsage":0,"safetyStock":0,"requiredStock":2},{"season":"fall","leadTime":1,"dailyUsage":0,"safetyStock":0,"requiredStock":2}]'::jsonb, '["tag-k1","tag-k4"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-069', 'kitchen', '롱고바디', 'food', 'room-temp', '캔', '개', 4, 0.5, 1, 1, '[{"season":"winter","leadTime":1,"dailyUsage":1,"safetyStock":3,"requiredStock":4},{"season":"spring","leadTime":1,"dailyUsage":0.5,"safetyStock":1,"requiredStock":2},{"season":"summer","leadTime":1,"dailyUsage":0.5,"safetyStock":1,"requiredStock":2},{"season":"fall","leadTime":1,"dailyUsage":0.5,"safetyStock":1,"requiredStock":2}]'::jsonb, '["tag-k7"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-070', 'kitchen', '토마토페이스트', 'food', 'room-temp', '캔', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k6","tag-k12"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-071', 'kitchen', '팩와인_레드', 'food', 'room-temp', '상온소스', '개', 1, 0, 2, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k15","tag-k14"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-072', 'kitchen', '팩와인_화이트', 'food', 'room-temp', '상온소스', '개', 1, 0, 2, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '[]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-073', 'kitchen', '발사믹', 'food', 'room-temp', '상온소스', '개', 5, 0.1, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k8"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-074', 'kitchen', '화이트와인비네거', 'food', 'room-temp', '상온소스', '개', 2, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k8"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-075', 'kitchen', '샴페인비네거', 'food', 'room-temp', '상온소스', '개', 3, 0, 2, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k16"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-076', 'kitchen', '타바스코150ml', 'food', 'room-temp', '상온소스', '개', 5, 0, 1, 3, '[{"season":"winter","requiredStock":3},{"season":"spring","requiredStock":3},{"season":"summer","requiredStock":3},{"season":"fall","requiredStock":3}]'::jsonb, '["tag-k1"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-077', 'kitchen', '메이플시럽', 'food', 'room-temp', '상온소스', '개', 3, 0, 3, 3, '[{"season":"winter","requiredStock":3},{"season":"spring","requiredStock":3},{"season":"summer","requiredStock":3},{"season":"fall","requiredStock":3}]'::jsonb, '["tag-k5"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k2', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-078', 'kitchen', '꿀', 'food', 'room-temp', '상온소스', '개', 2, 0, 2, 2, '[{"season":"winter","requiredStock":2},{"season":"spring","requiredStock":2},{"season":"summer","requiredStock":2},{"season":"fall","requiredStock":2}]'::jsonb, '["tag-k2","tag-k7"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-079', 'kitchen', '이금기치킨스톡농축액', 'food', 'room-temp', '상온소스', '개', 2, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k12","tag-k4","tag-k8","tag-k15"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-080', 'kitchen', '피스타치오스프레드', 'food', 'room-temp', '상온소스', '개', 2, 0, 1, 1, '[{"season":"winter","requiredStock":2},{"season":"spring","requiredStock":2},{"season":"summer","requiredStock":2},{"season":"fall","requiredStock":2}]'::jsonb, '["tag-k10"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k4', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-081', 'kitchen', '이탈리안허브시즈닝', 'food', 'room-temp', '상온소스', '개', 3, 0, 1, 1, '[{"season":"winter","requiredStock":2},{"season":"spring","requiredStock":2},{"season":"summer","requiredStock":2},{"season":"fall","requiredStock":2}]'::jsonb, '["tag-k1","tag-k13","tag-k14"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-082', 'kitchen', '파프리카시즈닝', 'food', 'room-temp', '상온소스', '개', 2, 0, 1, 2, '[{"season":"winter","requiredStock":2},{"season":"spring","requiredStock":2},{"season":"summer","requiredStock":2},{"season":"fall","requiredStock":2}]'::jsonb, '["tag-k1","tag-k7"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-083', 'kitchen', '오레가노', 'food', 'room-temp', '건허브&향신료', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k1"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-084', 'kitchen', '바질잎드', 'food', 'room-temp', '건허브&향신료', '개', 2, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k1"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-085', 'kitchen', '통흑후추', 'food', 'room-temp', '건허브&향신료', '개', 2, 0, 1, 1, '[{"season":"winter","requiredStock":2},{"season":"spring","requiredStock":2},{"season":"summer","requiredStock":2},{"season":"fall","requiredStock":2}]'::jsonb, '["tag-k6","tag-k8","tag-k9","tag-k11"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-086', 'kitchen', '백후추', 'food', 'room-temp', '건허브&향신료', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k4"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-087', 'kitchen', '핑크페퍼', 'food', 'room-temp', '건허브&향신료', '개', 1, 0, 2, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '[]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-088', 'kitchen', '베트남고추', 'food', 'room-temp', '건허브&향신료', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k13"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-089', 'kitchen', '시나몬파우더', 'food', 'room-temp', '건허브&향신료', '개', 3, 0, 1, 1, '[{"season":"winter","requiredStock":3},{"season":"spring","requiredStock":3},{"season":"summer","requiredStock":3},{"season":"fall","requiredStock":3}]'::jsonb, '["tag-k5"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k2', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-090', 'kitchen', '피칸', 'food', 'room-temp', '건허브&향신료', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k2","tag-k9"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-091', 'kitchen', '아몬드', 'food', 'room-temp', '견과류&곡물류', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k2","tag-k7","tag-k9"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-092', 'kitchen', '캐슈넛', 'food', 'room-temp', '견과류&곡물류', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k2","tag-k9"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-093', 'kitchen', '오트밀', 'food', 'room-temp', '견과류&곡물류', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k5"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-094', 'kitchen', '해바라기씨', 'food', 'room-temp', '견과류&곡물류', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k5"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-095', 'kitchen', '호박씨', 'food', 'room-temp', '견과류&곡물류', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k5"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-096', 'kitchen', '헤이즐넛', 'food', 'room-temp', '견과류&곡물류', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k5"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-097', 'kitchen', '코코넛롱(코코넛슬라이스)', 'food', 'room-temp', '견과류&곡물류', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k5"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-098', 'kitchen', '구운소금', 'food', 'room-temp', '가루류', '개', 4, 0, 2, 3, '[{"season":"winter","requiredStock":3},{"season":"spring","requiredStock":3},{"season":"summer","requiredStock":3},{"season":"fall","requiredStock":3}]'::jsonb, '["tag-k6","tag-k7","tag-k8"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-099', 'kitchen', '천일염', 'food', 'room-temp', '가루류', '개', 1, 20.7, 2, 1, '[{"season":"winter","requiredStock":0},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k16"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-100', 'kitchen', '백설탕', 'food', 'room-temp', '가루류', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k5","tag-k6","tag-k10"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-101', 'kitchen', '황설탕', 'food', 'room-temp', '가루류', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k9","tag-k5"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-102', 'kitchen', '흑설탕', 'food', 'room-temp', '가루류', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k9"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-103', 'kitchen', '박력분', 'food', 'room-temp', '가루류', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k14","tag-k4"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-104', 'kitchen', '중력분', 'food', 'room-temp', '가루류', '개', 4, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k8"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-105', 'kitchen', '강력분', 'food', 'room-temp', '가루류', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '["tag-k17"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-106', 'kitchen', '호밀가루', 'food', 'room-temp', '가루류', '개', 2, 0, 1, 2, '[{"season":"winter","requiredStock":2},{"season":"spring","requiredStock":2},{"season":"summer","requiredStock":2},{"season":"fall","requiredStock":2}]'::jsonb, '["tag-k17"]'::jsonb, '2026-01-13', 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-107', 'kitchen', '니트릴장갑S', 'non-food', 'room-temp', '소모품', '개', 2, 0, 1, 2, '[{"season":"winter","requiredStock":2},{"season":"spring","requiredStock":2},{"season":"summer","requiredStock":2},{"season":"fall","requiredStock":2}]'::jsonb, '[]'::jsonb, NULL, 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-108', 'kitchen', '니트릴장갑L', 'non-food', 'room-temp', '소모품', '개', 2, 0, 1, 2, '[{"season":"winter","requiredStock":2},{"season":"spring","requiredStock":2},{"season":"summer","requiredStock":2},{"season":"fall","requiredStock":2}]'::jsonb, '[]'::jsonb, NULL, 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-109', 'kitchen', '비닐(소)', 'non-food', 'room-temp', '소모품', '개', 8, 0, 1, 8, '[{"season":"winter","requiredStock":8},{"season":"spring","requiredStock":8},{"season":"summer","requiredStock":8},{"season":"fall","requiredStock":8}]'::jsonb, '[]'::jsonb, NULL, 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-110', 'kitchen', '비닐(대)', 'non-food', 'room-temp', '소모품', '개', 3, 0, 1, 3, '[{"season":"winter","requiredStock":3},{"season":"spring","requiredStock":3},{"season":"summer","requiredStock":3},{"season":"fall","requiredStock":3}]'::jsonb, '[]'::jsonb, NULL, 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-111', 'kitchen', '위생장갑', 'non-food', 'room-temp', '소모품', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '[]'::jsonb, NULL, 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-112', 'kitchen', '종이호일', 'non-food', 'room-temp', '소모품', '개', 3, 0, 1, 3, '[{"season":"winter","requiredStock":3},{"season":"spring","requiredStock":3},{"season":"summer","requiredStock":3},{"season":"fall","requiredStock":3}]'::jsonb, '[]'::jsonb, NULL, 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-113', 'kitchen', '쿠킹호일', 'non-food', 'room-temp', '소모품', '개', 1, 0, 1, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '[]'::jsonb, NULL, 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-114', 'kitchen', '키친타올', 'non-food', 'room-temp', '소모품', '개', 7, 0, 2, 4, '[{"season":"winter","requiredStock":4},{"season":"spring","requiredStock":4},{"season":"summer","requiredStock":4},{"season":"fall","requiredStock":4}]'::jsonb, '[]'::jsonb, NULL, 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-115', 'kitchen', '유니랩', 'non-food', 'room-temp', '소모품', '개', 1, 0, 2, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '[]'::jsonb, NULL, 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-116', 'kitchen', '부탄가스', 'non-food', 'room-temp', '소모품', '개', 4, 0, 2, 1, '[{"season":"winter","requiredStock":4},{"season":"spring","requiredStock":4},{"season":"summer","requiredStock":4},{"season":"fall","requiredStock":4}]'::jsonb, '[]'::jsonb, NULL, 'normal', NULL, NULL, 'sup-k1', 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-117', 'kitchen', '주방세제', 'non-food', 'room-temp', '소모품', '개', 2, 0, 2, 2, '[{"season":"winter","requiredStock":2},{"season":"spring","requiredStock":2},{"season":"summer","requiredStock":2},{"season":"fall","requiredStock":2}]'::jsonb, '[]'::jsonb, NULL, 'normal', NULL, NULL, NULL, 0);
INSERT INTO inventory_items (id, team, name, main_category, storage_type, sub_category, unit, current_stock, daily_usage, lead_time, safety_stock, seasonal_requirements, menu_tags, check_date, order_status, ordered_quantity, ordered_at, supplier_id, is_favorite) VALUES ('item-118', 'kitchen', '식기세척기세제', 'non-food', 'room-temp', '소모품', '개', 1, 0, 3, 1, '[{"season":"winter","requiredStock":1},{"season":"spring","requiredStock":1},{"season":"summer","requiredStock":1},{"season":"fall","requiredStock":1}]'::jsonb, '[]'::jsonb, NULL, 'normal', NULL, NULL, 'sup-k1', 0);

-- ==============================================
-- 5. ITEM_ORDERS (발주 이력)
-- ==============================================

-- ==============================================
-- 완료 확인
-- ==============================================
SELECT 
  (SELECT COUNT(*) FROM inventory_items) as items_count,
  (SELECT COUNT(*) FROM menu_tags) as tags_count,
  (SELECT COUNT(*) FROM suppliers) as suppliers_count,
  (SELECT COUNT(*) FROM sub_categories) as subcategories_count;
